# Generated by Django 3.1.1 on 2020-10-03 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminar', '0002_auto_20201003_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='updated_At',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userseminar',
            old_name='updated_At',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='userseminar',
            name='seminar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userseminar', to='seminar.seminar'),
        ),
        migrations.AlterField(
            model_name='userseminar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userseminar', to=settings.AUTH_USER_MODEL),
        ),
    ]
