# Generated by Django 3.1.1 on 2020-10-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201003_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorprofile',
            old_name='updated_At',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='participantprofile',
            old_name='updated_At',
            new_name='updated_at',
        ),
    ]
